### ISSUE TITLE
Blank installer due to python error

### ISSUE THREAD

**Issue by SmiVan** [rockerbacon/modorganizer2-linux-installer#179]
* Ubuntu 20.04.1 LTS
* Lutris 0.5.8
* Python 3.8.5
* MO2 install script 2.8.6

---

Running `lutris -i ~/Downloads/modorganizer2.yml` with the 2.8.6 Stable install script generates the following python error and a broken installer window:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 456, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 252, in show_installer_window
    self.show_window(
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in show_window
    window_inst = window_class(application=self, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 97, in __init__
    self.choose_installer()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 123, in choose_installer
    self.validate_scripts()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 115, in validate_scripts
    script[item] = script.get(item) or ""
AttributeError: 'str' object has no attribute 'get'
```
![Broken installer window](https://user-images.githubusercontent.com/7703934/100692821-b33d8400-339c-11eb-99cc-cf49347cbf59.png)

**Comment by SmiVan** [comment]
Alright turns out this is an upstream problem:
https://github.com/lutris/lutris/issues/3290

**Comment by XMais** [comment]
https://github.com/lutris/lutris/issues/3290

Downgrade to lutris 0.5.7.1 as I've told you in the other issue you posted.
Lutris 0.5.8 is a broken pos right now.
