### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Mojo9** [rockerbacon/modorganizer2-linux-installer#193]
Hey i found this great Git by chance and wantd to give it a try but already in the install I get this error. 

```
lutris -i "modorganizer282.yml"
Unable to load locale dir, translations won't work.
2020-12-11 22:44:30,433: Lutris 0.5.8
2020-12-11 22:44:30,433: Using NVIDIA drivers 455.45.01 for x86_64
2020-12-11 22:44:30,433: GPU: GeForce GTX 970
2020-12-11 22:44:30,433: GPU: 10DE:13C2 1462:3160 (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 456, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 252, in show_installer_window
    self.show_window(
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 246, in show_window
    window_inst = window_class(application=self, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 97, in __init__
    self.choose_installer()
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 123, in choose_installer
    self.validate_scripts()
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 115, in validate_scripts
    script[item] = script.get(item) or ""
AttributeError: 'str' object has no attribute 'get'

```
is it a dependency problem and why I get a Unable to load locale dir? I try to run this on my second HDD

**Comment by wezel** [comment]
Hey I ran into the same issue. After some poking around I believe it is a bug in the yaml loader for lutris. I fixed it by making a small change to the lutris code. If you know what you are doing you could make this change yourself. 
Open this file "/usr/lib/python3.8/site-packages/lutris/installer/__init__py".
got to line 49 and change the following:
from: return read_script(installer_file)
to: return [read_script(installer_file)]
that should fix it. Lutris for some reason expects it to be a list of scripts which it is not thus the error.

**Comment by wezel** [comment]
An easier temporarily fix would be to edit the yaml file. add a new line "script:" at the top and add 2 spaces at the front of each next line.

**Comment by Mojo9** [comment]
Thank you, this actually solved the problem.
I added the Brackets. Now I need to figuer out how to solve my second problem that he says i dont have the game ( because i only have it over family share)
Thanks again for taking your time to explain the fix for me!

**Comment by fighuass** [comment]
Hm, there's no "/usr/lib/python3.8/site-packages/lutris/installer/init.py" for me. In fact, the whole site-packages thing and what comes after isn't even there.

**Comment by fighuass** [comment]
Fixed it, it was in /usr/lib/python3/dist-packages/lutris/installer instead of /usr/lib/python3.8/site-packages/lutris/installer/ for me. The rest worked though!

**Comment by rockerbacon** [comment]
Closing as the latest version no longer uses Lutris
