### ISSUE TITLE
MO2 fails installing through Lutris

### ISSUE THREAD

**Issue by Italos021** [rockerbacon/modorganizer2-linux-installer#200]
Cant Download most of packages. This is the output of konsole:
Any help? :)

lutris -i modorganizer2.yml
Unable to load locale dir, translations won't work.

(lutris:15478): Gtk-WARNING **: 20:48:31.416: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:31.416: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:31.416: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2021-01-20 20:48:31,689: Initializing lutris
2021-01-20 20:48:32,195: Runtime up-to-date. Initialization complete.
2021-01-20 20:48:32,199: Lutris 0.5.8.1
2021-01-20 20:48:32,199: Running AMD Mesa driver 21.1.0 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.39.0, 5.9.16-1-MANJARO, LLVM 11.0.1) (0x731f)
2021-01-20 20:48:32,199: GPU: 1002:731F 1DA2:E409 (amdgpu drivers)

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:15478): Gtk-WARNING **: 20:48:32.270: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
2021-01-20 20:48:55,570: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e4e40d0>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /MWSE/MWSE/releases/download/build-automatic/mwse.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e4ef910>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:48:55,571: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /MWSE/MWSE/releases/download/build-automatic/mwse.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e4ef910>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
2021-01-20 20:49:00,431: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e651a90>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/find-library-for-appid.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e678820>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:00,431: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/find-library-for-appid.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e678820>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
2021-01-20 20:49:00,432: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e6554c0>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/dialog.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac147f9220>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:00,433: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/dialog.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac147f9220>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
2021-01-20 20:49:00,442: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e6703a0>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-runners/wine-launcher.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac141b3730>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:00,442: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-runners/wine-launcher.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac141b3730>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
2021-01-20 20:49:00,449: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac141b3850>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.6-handlers/modorganizer2-nxm-broker.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e6600d0>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:00,449: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.6-handlers/modorganizer2-nxm-broker.sh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e6600d0>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
2021-01-20 20:49:00,457: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e660280>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.6-handlers/modorganizer2-nxm-handler.desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e660580>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:00,457: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.6-handlers/modorganizer2-nxm-handler.desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e660580>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable
2021-01-20 20:49:05,461: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fac0e678910>>: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.5-gamesinfo/gamesinfo.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e612400>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
2021-01-20 20:49:05,461: Download failed: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /rockerbacon/lutris-skyrimse-installers/releases/download/2.8.5-gamesinfo/gamesinfo.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac0e612400>: Failed to establish a new connection: [Errno -2] Το όνομα ή η υπηρεσία δεν είναι γνωστά'))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/download_progress.py", line 94, in _progress
    self._set_text(self.downloader.error[:80])
TypeError: 'ConnectionError' object is not subscriptable

**Comment by Italos021** [comment]
Ok after downgraded lutris i managed at least to install vortex.

**Comment by kleshas** [comment]
As far as I know the installer only works for lutris 5.7.1.1 and installs MO2 2.2.1.  I tried updating MO2 via its own updater, which failed.

**Comment by Italos021** [comment]
I installed  MO2,  which is better imo! :)

**Comment by rockerbacon** [comment]
Closing as the latest version no longer uses Lutris.
