### ISSUE TITLE
Broken on Fedora 37 Due To Protontricks

### ISSUE THREAD

**Issue by cprin21** [rockerbacon/modorganizer2-linux-installer#426]
Getting an error trying to install mo2 on Fedora 37, seems to be a problem between protontricks and this install script.

```
INFO: applying protontricks xaudio2_7=native
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.10.0', 'console_scripts', 'protontricks')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 328, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 756, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 544, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 544, in <listcomp>
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 452, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
```

**Comment by Amazingbarrel** [comment]
> Got the same issue on EOS / Arch using the same protontricks version, [which is the most up to date package in the AUR](https://aur.archlinux.org/packages/protontricks).
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/protontricks", line 33, in <module>
>     sys.exit(load_entry_point('protontricks==1.10.0', 'console_scripts', 'protontricks')())
>   File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 32, in cli
>     main(args)
>   File "/usr/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
>     return cli_func(self, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 328, in main
>     proton_app = find_proton_app(
>   File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 756, in find_proton_app
>     tool_app = find_steam_compat_tool_app(
>   File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 544, in find_steam_compat_tool_app
>     appinfo_sections = [
>   File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 544, in <listcomp>
>     appinfo_sections = [
>   File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 452, in iter_appinfo_sections
>     raise SyntaxError("Invalid file magic number")
> SyntaxError: Invalid file magic number
> ```
> 
> A bit confused what the solution here is supposed to be since the project clearly lists protontricks as a hard dependency and I also need it for other games (where it works fine).

using protontricks-git solved it for me. idk how, but it did.
