### ISSUE TITLE
Error during install of MO2

### ISSUE THREAD

**Issue by Thegrayjedi** [rockerbacon/modorganizer2-linux-installer#450]
So after running the script, everything is downloading and installing just fine until this section:

```
INFO: applying protontricks xaudio2_7=native
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
```

Any ideas? I really need to get this installed so I can mod Fallout4. Thanks!

**Comment by largereptile** [comment]
similar situation but for FNV, proton version lines up and there arent any launch options

```(base) harry@harrubuntu:~/Downloads/mo2installer$ ./install.sh
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/harry/.steam/debian-installation'
INFO: steam not found in '/home/harry/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/harry/.steam/debian-installation'
INFO: selected install directory '/home/harry/Games/mod-organizer-2-newvegas'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing existing JDK installation in '/home/harry/.steam/debian-installation/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing JDK in '/home/harry/.steam/debian-installation/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/harry/Games/mod-organizer-2-newvegas/modorganizer2'
INFO: installing script extender in '/home/harry/.steam/debian-installation/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/harry/.steam/debian-installation/steamapps/common/Fallout New Vegas'
INFO: installing nxm link broker in '/home/harry/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/harry/.local/share/applications/'
INFO: applying protontricks d3dcompiler_43 d3dx9
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
```

**Comment by largereptile** [comment]
nevermind, it was an issue with protontricks being the wrong version - @Thegrayjedi 

on Ubuntu 22.04 the version of protontricks you get via apt is 1.7. If you follow their install guide to use flatpak then it worked for me.

https://github.com/Matoking/protontricks

**Comment by Thegrayjedi** [comment]
I'll try that when I can, thanks @largereptile

**Comment by DominicWatson** [comment]
@largereptile @Thegrayjedi I'd recommend NOT going with the Flatpak version. This caused issues for me that meant various problems in MO2 due to permissions.

Instead, the only thing that worked for me is installing using `pipx`. You get the latest version + no file permissioning issues. YMMV.

So install pipx, e.g. `apt install pipx` if using debian/ubuntu based. Then:

```
pipx install protontricks
```

**Comment by largereptile** [comment]
Fair dos, I just reconfigured the permissions for flatpak - I think they've got alright instructions for it on the protontricks github

**Comment by Thegrayjedi** [comment]
Flatpak version worked for me just fine. True, MO2 spits out errors like nobody's business, but they seem to be text or display related errors. AKA, nothing new in WINE.

In short, if anyone is having issues installing MO2 that matches the "Magic Number" error, it is the ProtonTricks version mismatch, you need 1.10.1.

That error should be renamed, but meh. We figured it out.
