### ISSUE TITLE
Issue - Magic Number? (Linux Mint)

### ISSUE THREAD

**Issue by SatakalTheEternal** [rockerbacon/modorganizer2-linux-installer#486]
Hey sorry for the confusing title, I'm not exactly a seasoned user of a very techy guy in general. I know enough to extract a source tarball and install but that's about it. So while installing everything seemed to be going smoothly until the program gave me an error, saying "Operation canceled. Check the terminal for details". Originally I was using the GUI installer so I didn't have a terminal open, so I decided to reinstall using the terminal. This is what I got:

```
koschei@koschei-B450M-DS3H:~$` cd mo2installer-4_3_0
koschei@koschei-B450M-DS3H:~/mo2installer-4_3_0$ ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/koschei/.steam/debian-installation'
INFO: steam not found in '/home/koschei/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/koschei/.steam/debian-installation'
INFO: selected install directory '/home/koschei/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://skse.silverlock.org/beta/skse64_2_01_05.7z'
INFO: downloading 'https://skse.silverlock.org/beta/skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
INFO: removing existing JDK installation in '/home/koschei/.steam/debian-installation/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing JDK in '/home/koschei/.steam/debian-installation/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/koschei/Games/mod-organizer-2-skyrimspecialedition/modorganizer2'
INFO: installing script extender in '/home/koschei/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/Data' into '/home/koschei/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_1_6_353.dll' into '/home/koschei/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_loader.exe' into '/home/koschei/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_steam_loader.dll' into '/home/koschei/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: installing nxm link broker in '/home/koschei/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/koschei/.local/share/applications/'
INFO: applying protontricks xaudio2_7=native
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_protontricks.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
```

I legitimately cannot really interpret this. I assume it has something to do with "SyntaxError: Invalid file magic number" but I don't know what the issue is with that is (BTW if some mod here wants to format this better I would welcome it).

Anyhow it did create an MO2 folder and when I went there it was a bunch of .exe files and folders and whatnot. I tried running ModOrganizer.exe with protontricks with the Skyrim Special Ediition prefix and this is what it gives me.

```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/launch.py", line 152, in main
    cli_main(cli_args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number


=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/koschei/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Found 1 Steam library folders
Currently logged-in Steam user: [my steam name]
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider
Calling `protontricks` with the command: ['-c', "wine '/home/koschei/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/ModOrganizer.exe'", '489830']
Found Steam directory at /home/koschei/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/koschei/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: [my steam name]
Couldn't find custom shortcuts. Maybe none have been created yet?
```

Once again there's the Invalid file magic number. Anyone know what could be the issue here? I saw a user had a similar issue and his fix was to use the pipx version of protontricks but I still got the same error after doing that. It also said I need a specific version (1.10.1) but I don't know how to retrieve that or what the latest version is.

**Comment by SatakalTheEternal** [comment]
Alright so the issue was getting the most recent version of protontricks (1.10.3) from a mirror, the one on synaptic is outdated. Here's the one I used: https://pypi.org/project/protontricks/
