### ISSUE TITLE
operation failed

### ISSUE THREAD

**Issue by hydropump91** [rockerbacon/modorganizer2-linux-installer#514]
hi i am new with linux and my installation always failed... thank you for your help

INFO: all dependencies met

(process:16587): Gtk-WARNING **: 23:55:40.889: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: selected game 'skyrimspecialedition'

(process:16606): Gtk-WARNING **: 23:56:50.728: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'

(process:16623): Gtk-WARNING **: 23:56:56.723: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:16640): Gtk-WARNING **: 23:57:00.255: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: selected install directory '/home/deck/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'

(process:16653): Gtk-WARNING **: 23:57:01.844: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'

(process:16674): Gtk-WARNING **: 23:57:44.600: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'

(process:16684): Gtk-WARNING **: 23:57:45.521: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'

(process:16708): Gtk-WARNING **: 23:59:51.327: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'

(process:16719): Gtk-WARNING **: 23:59:58.106: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: using wget backend
INFO: fetching remote resource at 'https://skse.silverlock.org/beta/skse64_2_02_03.7z'
INFO: downloading 'https://skse.silverlock.org/beta/skse64_2_02_03.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'

(process:16732): Gtk-WARNING **: 00:00:02.982: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'

(process:16751): Gtk-WARNING **: 00:00:05.227: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: installing JDK in '/home/deck/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/java'

(process:16767): Gtk-WARNING **: 00:00:05.374: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:16774): Gtk-WARNING **: 00:00:05.493: Locale not supported by C library.
        Using the fallback 'C' locale.
INFO: installing Mod Organizer 2 in '/home/deck/Games/mod-organizer-2-skyrimspecialedition/modorganizer2'
INFO: installing script extender in '/home/deck/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03/skse64_2_02_03/Data' into '/home/deck/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03/skse64_2_02_03/skse64_1_6_640.dll' into '/home/deck/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03/skse64_2_02_03/skse64_loader.exe' into '/home/deck/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: installing nxm link broker in '/home/deck/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/deck/.local/share/applications/'
INFO: applying protontricks xaudio2_7=native

(process:16801): Gtk-WARNING **: 00:00:09.529: Locale not supported by C library.
        Using the fallback 'C' locale.
protontricks (WARNING): Steam library folder /run/media/mmcblk0p1 not found. Protontricks might not have access to the directory.
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 360, in main
    returncode = run_command(
  File "/app/lib/python3.10/site-packages/protontricks/util.py", line 339, in run_command
    raise RuntimeError(
RuntimeError: Proton 8.0 is missing the required Steam Runtime. You may need to launch a Steam app using this Proton version to finish the installation.
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

(process:16844): Gtk-WARNING **: 00:00:10.601: Locale not supported by C library.
        Using the fallback 'C' locale.

**Comment by rockerbacon** [comment]
Closing due to inactivity.
