### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by splitface2811** [rockerbacon/modorganizer2-linux-installer#521]
When trying to install I get the following:

```shell
josh@pop-os:~/Documents/Mod Organizer Installer$ ./install.sh 
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/josh/.steam/debian-installation'
INFO: game not found in '/home/josh/.steam/debian-installation'
INFO: game not found in '/Left_Testicle/SteamLibrary'
INFO: game found in '/SSD_Data/SteamLibrary'
INFO: steam not found in '/home/josh/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

``` 

It doesn't seem to install anything, and launching the game works as normal.

**Comment by rockerbacon** [comment]
The issue is with Protontricks. Your logs suggest you may be using Protontricks 1.7.0, which is extremely outdated.

Try installing a newer version of Protontricks.
