### ISSUE TITLE
When i try to set up mo2 for any game it throws me an error saying "invalid file magic number"

### ISSUE THREAD

**Issue by TerribleMunster** [rockerbacon/modorganizer2-linux-installer#535]
```
INFO: all dependencies met
INFO: selected game 'skyrim'
INFO: found Steam in '/home/[username]/.steam/debian-installation'
INFO: game not found in '/home/[username]/.steam/debian-installation'
INFO: found Steam in '/home/[username]/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/hdd/SteamLibrary'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
```

 im clueless any sort of help apriciated thanks!

**Comment by Mathieu265** [comment]
Had the same issue for me what fixed it was installing protontricks as flatpak not natively

**Comment by purritothecoolcat** [comment]
Oh, uninstall protontricks **COMPLETELY** and then install it via pipx, flatpak uses an older version that is no longer compatible.
