### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by corigne** [rockerbacon/modorganizer2-linux-installer#728]
Arch linux, protontricks and steam from AUR, recently updated, install fails citing invalid magic number. 

Environment:
![image](https://github.com/user-attachments/assets/e27356c2-2e95-4fa2-a6ef-7ce35f1e6158)

Running Intall:
```
~/D/mo2installer-5.0.3 29.1s  STEAM_LIBRARY=/home/nexus/.local/share/Steam/ ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 357, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n
```

**Comment by corigne** [comment]
Did some investigation after I sobered up. It looks like the problem is incompatibilities between Steam Beta Client and current protontricks.

Per https://github.com/Matoking/protontricks/issues/304 recent changes to the Steam Beta Client appinfo.vdf has changed rather dramatically causing issue in the way protontricks parses the appinfo.vdf.

Current fix is to downgrade from Steam Beta to the standard Steam client.

**Comment by corigne** [comment]
Also, its totally fine if you want to re-open this for tracking, I just figure since it's protontricks and not this script at fault it should be closed.
