### ISSUE TITLE
Protontricks did not find a valid prefix directory. SkyrimSE

### ISSUE THREAD

**Issue by nicolasmdf** [rockerbacon/modorganizer2-linux-installer#732]
Everything is up-to-date, here is the full output I get after selecting SkyrimSE from the menu:

INFO: all dependencies met

(zenity:6263): Gtk-WARNING **: 12:54:00.142: Unknown key gtk-modules in /home/nicolas/.config/gtk-4.0/settings.ini

(zenity:6263): Adwaita-WARNING **: 12:54:00.218: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/nicolas/.local/share/Steam'
INFO: game found in '/home/nicolas/.local/share/Steam'
INFO: steam not found in '/home/nicolas/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n

Using latest EndeavourOS, tried several different versions of Proton within the Steam interface including the latest Proton-GE. No flatpaks.

**Comment by CorruptComputer** [comment]
Seeing the same issue on Arch as well:

```bash
$ ./install.sh 
INFO: all dependencies met

(zenity:46667): Gtk-WARNING **: 23:25:27.390: Unknown key gtk-modules in /home/user/.config/gtk-4.0/settings.ini

(zenity:46667): Adwaita-WARNING **: 23:25:27.449: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/user/.local/share/Steam'
INFO: game not found in '/home/user/.local/share/Steam'
INFO: game found in '/mnt/cueball/SteamLibrary'
INFO: steam not found in '/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n
```

**Comment by rockerbacon** [comment]
Clearly a protontricks issue

**Comment by nicolasmdf** [comment]
Yes. Took me a while to figure it out.
For anyone having the same problem, I just opted out of Steam's beta. Then it worked fine.

**Comment by hrqmonteiro** [comment]
> Yes. Took me a while to figure it out. For anyone having the same problem, I just opted out of Steam's beta. Then it worked fine.

And how does one does this? I didn't even know that i was on Steam Beta, if that is the problem

**Comment by RahboLeo** [comment]
Not sure about the "steam beta" but I was able to fix this issue using the flatpack version instead of the system package version

**Comment by Violet-RM** [comment]
Debian Testing with protontricks flatpak. Any guidance would be appreciated 
`./install.sh
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/v/.steam/debian-installation'
INFO: game found in '/home/v/.steam/debian-installation'
INFO: steam not found in '/home/v/.var/app/com.valvesoftware.Steam/.local/share/Steam'
/usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 406, in main
    returncode = run_command(
                 ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/util.py", line 516, in run_command
    raise RuntimeError(
RuntimeError: bwrap launcher crashed, returncode: 127
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n`
