### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by ShadowReaper420** [rockerbacon/modorganizer2-linux-installer#738]
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/flugel/.local/share/Steam'
INFO: game not found in '/home/flugel/.local/share/Steam'
INFO: steam not found in '/home/flugel/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/run/media/flugel/Modding/SteamLibrary'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 361, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 860, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 621, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 543, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n
/usr/bin/kitty failed with error: exit s

**Comment by ShadowReaper420** [comment]
Duplicate
