### ISSUE TITLE
getting some wierd syntax issues (Help)

### ISSUE THREAD

**Issue by FriendlyConstructGamer** [rockerbacon/modorganizer2-linux-installer#739]
hey new to linux need some help with some stuff running NOBARA 
![Screenshot_20240915_151816](https://github.com/user-attachments/assets/a7ee4294-6a7f-432f-90de-d95dbca02db9)

ive followed all instructions but no matter where i install Skyrim special edition through steam it comes up with this error

INFO: all dependencies met

(zenity:31433): Gtk-WARNING **: 15:11:18.947: Unknown key gtk-modules in /etc/xdg/gtk-4.0/settings.ini

(zenity:31433): Gtk-WARNING **: 15:11:18.947: Unknown key gtk-modules in /home/ben/.config/gtk-4.0/settings.ini

(zenity:31433): Gtk-WARNING **: 15:11:18.957: Theme directory actions/32 of theme Papirus-Colors-Dark has no size field

(zenity:31433): Adwaita-WARNING **: 15:11:19.128: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:31433): Gtk-WARNING **: 15:11:19.167: Theme directory actions/32 of theme Papirus-Colors-Dark has no size field

(zenity:31433): Gtk-WARNING **: 15:11:19.333: Failed to load icon /usr/share/icons/Papirus-Colors-Dark/actions/16/system-search-symbolic.svg: Failed to open file “/usr/share/icons/Papirus-Colors-Dark/actions/16/system-search-symbolic.svg”: No such file or directory
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/ben/.local/share/Steam'
INFO: game found in '/home/ben/.local/share/Steam'
INFO: steam not found in '/home/ben/.var/app/com.valvesoftware.Steam/.local/share/Steam'
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n
arch-symbolic.svg”: No such file or directory
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/ben/.local/share/Steam'
INFO: game found in '/home/ben/.local/share/Steam'
INFO: steam not found in '/home/ben/.var/app/com.valvesoftware.Steam/.local/share/Steam'
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n

**Comment by rockerbacon** [comment]
https://github.com/Matoking/protontricks/issues/304
